export const LOAD_DASHBOARD_DATA = 'LOAD_DASHBOARD_DATA';
export const BEGIN_LOAD_DASHBOARD_DATA = 'BEGIN_LOAD_DASHBOARD_DATA';

export const LOAD_REGISTER_LIST_DATA = 'LOAD_REGISTER_LIST_DATA';
export const LOAD_MORE_REGISTER_LIST_DATA = 'LOAD_MORE_REGISTER_LIST_DATA';
export const BEGIN_LOAD_REGISTER_LIST_DATA = 'BEGIN_LOAD_REGISTER_LIST_DATA';

export const UPDATE_LOGIN_FORM = 'UPDATE_LOGIN_FORM';
